name: db_client
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.13.3
  firedart: ^0.9.7
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  http: ^1.1.0
  uuid: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
